### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by ndikumanaisaie** [RitobrotoMukherjee/to-do-list-webpack#4] opened 2022-06-07 07:37 UTC
### Good job so far, however, there is a small issue in your code that should be addressed.

- Kindly remove the commented lines of code in the `tasklist.js` file from lines [16 - 18](https://github.com/RitobrotoMukherjee/to-do-list-webpack/blob/f511170b549170aecb8c5cfb047e47f18a1e1cf3/src/js/taskList.js#L16:L18). Commented lines of code will make your codebase look messy.

**Comment by RitobrotoMukherjee** [comment] 2022-06-14 07:22
@ndikumanaisaie  Thanks for your feedback. The issue is now fixed.

**Closed by RitobrotoMukherjee** 2022-06-14 07:22 UTC
